
import {Ubuntu}  from 'next/font/google'

import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";


const ubuntu = Ubuntu({
  weight: ['300','400','500','700'],
  subsets : ['latin'],
  variable: '--font-ubuntu',
})

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${ubuntu.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
